### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by kaanselhep** [parse-community/parse-server-simple-mailgun-adapter#16]
Hey,

I tried integrating this using npm install parse-server-simple-mailgun-adapter and couldn't get it to work. Maybe my domain settings are not configured properly on mailgun as the DNS records is showing a little error next to them on mailgun. How do I configure those for a server sitting at heroku.

My parse app is sitting on heroku. It's here: https://bookupapp.herokuapp.com

Can someone please write a good detailed tutorial on how to integrate this??

Regards.

**Comment by kaanselhep** [comment]
@drew-gross just to get your attention please.

**Comment by kaanselhep** [comment]
Found this, but haven't tried it out yet: https://www.npmjs.com/package/mailgun-js
Any help is appreciated...

**Comment by PunkStarStudios** [comment]
Bump.
Hey - some instructions on how to get this thing working would be brilliant :)

**Comment by mtrezza** [comment]
Closing; this mail adapter has been deprecated.
