### ISSUE TITLE
What To Put as Mailgun Public Server URL

### ISSUE THREAD

**Issue by fprospato** [parse-community/parse-server-simple-mailgun-adapter#23]
I have implemented parse-server-simple-mailgun-adapter with my Parse server to send email verifications and reset password emails. Everything is working perfectly fine, but I am concerned about the publicServerURL part because as of now I used my serverURL for this. So now when an email verification or a reset password email is sent, the link in the email body shows my serverURL, which is something I do not want.

So what can I put under publicServerURL?? Should I put the URL the projects website or is there another alternative? I have not found any information on this.

**Comment by acinader** [comment]
the parse-server-simple-mailgun-adapter doesn't have a publicServerURL key.  I assume you mean parse-servers.  Putting the address of your server and having the verification links go to that server makes sense.  I am closing this, you can reopen with more info.
