### ISSUE TITLE
Server.js  / AWS

### ISSUE THREAD

**Issue by amitkh6** [parse-community/parse-server-simple-mailgun-adapter#28]
After updating server.js for AWS somehow parse stop running below is the status.

emailAdapter: {
module: 'parse-server-mailgun',
options: {
// The address that your emails come from
fromAddress: 'xxx',
// Your domain from mailgun.com
domain: 'xxx',
// Your API key from mailgun.com
apiKey: 'key-xxx',
// The template section
}
}

----Status---

$ sudo /opt/bitnami/ctlscript.sh status
apache already running
parse not running
mongodb already running

**Comment by flovilmart** [comment]
Did you install and provide the mailgun adapter?

**Comment by amitkh6** [comment]
Yes I did, it threw errors

Location apps/parse/htdocs

**Comment by flovilmart** [comment]
We’re not familiar with bitnami images. If the server is not running it probably means an error was thrown. Did you check the logs?

**Comment by amitkh6** [comment]
Below is the error i got for installation


bitnami@ip-172-31-1-178:~/apps/parse/htdocs$ npm install --save @parse/simple-mailgun-adapter
npm ERR! file /opt/bitnami/apps/parse/htdocs/package.json
npm ERR! code EJSONPARSE
npm ERR! Failed to parse json
npm ERR! Unexpected end of JSON input while parsing near ''
npm ERR! File: /opt/bitnami/apps/parse/htdocs/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bitnami/.npm/_logs/2018-10-03T07_46_05_361Z-debug.log
bitnami@ip-172-31-1-178:~/apps/parse/htdocs$

**Comment by flovilmart** [comment]
This is quite explicit, your package.json file is not a valid JSON.
