### ISSUE TITLE
Reciever email address is "undefined" in mail body

### ISSUE THREAD

**Issue by smatisen** [parse-community/parse-server-simple-mailgun-adapter#5]
Somehow there should be an email, but only "undefined" for now.

**Comment by hramos** [comment]
@smatisen can you provide a bit more detail?

**Comment by smatisen** [comment]
Parser Server on Heroku
Action: confirm email.
Message: Hi, You are being asked to confirm the e-mail address undefined with _app_name_

Link is correct, all working well. Exept I cant change the template to fix that "undefined".
