### ISSUE TITLE
Emails not getting delivered

### ISSUE THREAD

**Issue by amritsub** [parse-community/parse-server-simple-mailgun-adapter#6]
Running a parse-server-example project locally, have my index.js configured as so:

```
var api = new ParseServer({
  verifyUserEmails: true,
  databaseURI: databaseUri || 'mongodb://localhost:27017/dev',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'XXX',
  masterKey: process.env.MASTER_KEY || 'XXX', //Add your master key here. Keep it secret!
  serverURL: process.env.SERVER_URL || 'http://localhost:1337/parse',  // Don't forget to change to https if needed
  liveQuery: {
    classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
  },
  publicServerURL: 'https://XXX.ngrok.io',
  appName: 'Apex',
  emailAdapter: {
    module: 'parse-server-simple-mailgun-adapter',
    options: {
      // The address that your emails come from
      fromAddress: 'XXX@XXX.com',
      // Your domain from mailgun.com
      domain: 'sandboxXXX.mailgun.org',
      // Your API key from mailgun.com
      apiKey: 'key-XXX',
    }
  },
});
```

when the reset request is sent, ngrok shows the request returning '200 OK' but no email is received. Mailgun shows no email being sent. no error message is shown, is there anything I can do to enhance logging or any additional config I need to do? Thanks

**Comment by msniff16** [comment]
same

**Comment by borohhov** [comment]
I have the same setup on Heroku, and my application returns 503 internal server error. Obviously, something is missing, can anyone post a more detailed instruction on how to setup parse-server-example.

**Comment by amritsub** [comment]
for anyone else with this problem, solution is here: http://stackoverflow.com/questions/36671301/how-do-you-configure-an-emailadapter-for-parse-server. I needed publicServerURL to match the serverUrl.

**Comment by gyrotechnologies** [comment]
If you're using a sandbox domain with mailgun, only authorised recipients will receive emails. You need to set the authorised recipients within the domain settings

**Comment by celclar** [comment]
So then, it is impossible to use automatic email verification with a mailgun free plan?!?

**Comment by flovilmart** [comment]
@celclar the free plan allows for 10000 emails / months + 100 validations

**Comment by celclar** [comment]
@flovilmart, but If you need to previously authorize a recipient (as @gyrotechnologies said before), how can the automatic email verification email be sended?

**Comment by flovilmart** [comment]
> but If you need to previously authorize a recipient, how can be the automatic email verification email be sended?

I believe this is only the case in the sandbox domain.

**Comment by celclar** [comment]
@flovilmart  I create a new Malgun account 3 days ago, for a new project, add a custom domain (in the EU region, but mailgun verify correctly all the dns records), and I can't choose if it's sandbox or not. But then when I test it throught API console command, it messages me: "Free accounts are for test purposes only. Pleas upgrade or add the address to authorized recipients in Account Settings."
So... am I missing something?

**Comment by flovilmart** [comment]
@celclar I am not sure, but you should probably register to an account, an leverage their free tier which gives you 10000 emails free per month. Or find another email provider which has more permissive free accounts. Also consider asking on stackoverlfow as I am not familiar with mailgun in particular nor their pricing strategy.

**Comment by gyrotechnologies** [comment]
@celclar In your Mailgun account, does it say that your custom domain is active? If so, have you changed the the domain in your parse server mail adapter to your custom domain?

**Comment by celclar** [comment]
@gyrotechnologies  Yes It's active, and well configured.
They(maligun) told me that sandboxes and free plans are not able to send without authorize previously the recipient (unlike a while ago)... thats a pity
