### ISSUE TITLE
Customize pages

### ISSUE THREAD

**Issue by MattiaConfalonieri** [parse-community/parse-server-simple-mailgun-adapter#7]
Is possible customize html page like Parse?

**Comment by majidhassan** [comment]
The HTML templates:
- invalid_link.html
- password_reset_success.html
- verify_email_success.html

can be found under `/usr/lib/node_modules/parse-server/public_html`.

**Comment by johncodeos** [comment]
I'm using parse-server-example and I can't find this folder in this path.

**Comment by johncodeos** [comment]
oh, I found it! it's `myparse-server/node_modules/parse-server/public_html`
