### ISSUE TITLE
Specific instructions on how to add mailgun adapter... 

### ISSUE THREAD

**Issue by lamarrg** [parse-community/parse-server-simple-mailgun-adapter#9]
I am looking for more detailed instructions on and how to properly configure, and to get mailgun to work. I have about zero experience with Node, except from installing parse-server. It appears the tutorials assume a familiarity with node.js, its dependencies and abilities. Throughout the parse-server environment, the term "configuration file" (or something similar), is used without stating exactly which file is being referenced. (for those of us who don't know)

So far, this is what I have... 
-mailgun acct
-parse-server-example successfully installed on aws (deployed from EB CLI, but never ran locally)
-parse-dashboard installed locally and working (can't seem to get this deployed on EB)
-node modules installed locally (including mailgun adapter)

parse-server & parse-dashboard work as listed above. As soon as I add the code listed [here](https://github.com/ParsePlatform/parse-server#email-verification-and-password-reset) for mailgun, it breaks. I add it to the index.js that is running my parse-server. (is this the proper location?) I also have to comment out "...other options," or it creates its own error. 

I have removed the log files from earlier, it turns out that section is the same whether it works or not. Both show basically identical errors, except adding mailgun code breaks install...

**Comment by lamarrg** [comment]
ok, hours later, I think I have figured out some basics to get me moving forward...

**Comment by zirinisp** [comment]
Have you managed to get verification emails to work. In my case only the reset password is working.

For more information see the following question
http://stackoverflow.com/questions/39891896/parse-server-with-mailgun-adapter-how-can-i-get-verification-email-to-work

**Comment by emileNetter** [comment]
Hi @lamarrg !
Can you explain how you manage to get it working ? I have the same problem once i add emailadapter to my index.js parse is broke. Hope you see that !
